<?php

namespace Everis\Holamundo\Model\Resource;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class Holamundo extends AbstractDb{

    public function _construct(){
       $this->_init('everis_holamundo','entity_id');
    }

    public function _beforeSave(\Magento\Framework\Model\AbstractModel $object)
    {
        return parent::_beforeSave($object); // TODO: Change the autogenerated stub
    }

    public function _beforeDelete(\Magento\Framework\Model\AbstractModel $object)
    {
        return parent::_beforeDelete($object); // TODO: Change the autogenerated stub
    }

}
